kind: Service
apiVersion: v1
metadata:
  name: pim-service
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.HttpPort }}
  selector:
    app: pim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pim-deployment
  labels:
    app: pim
spec:
  replicas: 6
  selector:
    matchLabels:
      app: pim
  template:
    metadata:
      labels:
        app: pim
    spec:
      containers:
      - name: pim
        image: abderrazak/pim-service:1.0
        ports:
        - containerPort: 8080