kind: Service
apiVersion: v1
metadata:
  name: pim-service
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.HttpPort }}
  selector:
    app: pim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pim-deployment
  labels:
    mvp: true
    app: pim
    language: java
spec:
  replicas: {{ .Values.Replicas }}
  selector:
    matchLabels:
      app: pim
      mvp: true
      language: java
  template:
    metadata:
      labels:
        app: pim
    spec:
      containers:
      - name: pim
        image: {{ .Values.Image }}
        ports:
        - containerPort: 8080
